resources(
    name="test_files",
    sources=[
        "test_text.txt",
        "test_text_large.txt",
        "test_text_special_char.txt",
    ],
)

python_tests(
    dependencies=[
        ":test_files",
    ]
)
