python_sources(
    dependencies=[
        ":training_data",
    ]
)

resources(
    name="training_data",
    sources=[
        "tiny_shakespeare.txt",
        "training_data.txt",
        "*.pkl",
    ],
)